Document: networking-zvm
Title: Debian networking-zvm Manual
Author: <insert document author here>
Abstract: This manual describes what networking-zvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/networking-zvm/networking-zvm.sgml.gz

Format: postscript
Files: /usr/share/doc/networking-zvm/networking-zvm.ps.gz

Format: text
Files: /usr/share/doc/networking-zvm/networking-zvm.text.gz

Format: HTML
Index: /usr/share/doc/networking-zvm/html/index.html
Files: /usr/share/doc/networking-zvm/html/*.html
